### ISSUE TITLE
LCQMC dataset is no longer open-sourced

### ISSUE THREAD

**Issue by zburning** [dmlc/gluon-nlp#1144]
## Description
I'm running:
```
LCQMC = LCQMCTask()
print(len(LCQMC.dataset_train()[1]))
```
and it raise
Traceback (most recent call last):
  File "/Users/zechenw/Desktop/language_model/play.py", line 5, in <module>
    print(len(LCQMC.dataset_train()[1]))
  File "/Users/zechenw/Desktop/language_model/data/classification.py", line 75, in dataset_train
    return 'train', self.get_dataset(segment='train')
  File "/Users/zechenw/Desktop/language_model/data/classification.py", line 336, in get_dataset
    return BaiduErnieLCQMC(segment)
  File "/Users/zechenw/Desktop/language_model/data/baidu_ernie_data.py", line 159, in __init__
    field_indices=field_indices)
  File "/Users/zechenw/Desktop/language_model/data/baidu_ernie_data.py", line 47, in __init__
    super(_BaiduErnieDataset, self).__init__(filename, **kwargs)
  File "/Users/zechenw/Desktop/gluon-nlp/src/gluonnlp/data/dataset.py", line 134, in __init__
    super(TSVDataset, self).__init__(self._read())
  File "/Users/zechenw/Desktop/gluon-nlp/src/gluonnlp/data/dataset.py", line 153, in _read
    with io.open(filename, 'r', encoding=self._encoding) as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zechenw/.mxnet/datasets/baidu_ernie_data/task_data/lcqmc/train.tsv'

LCQMC is removed from task_data.tgz, and it requires application to the dataset owner. http://icrc.hitsz.edu.cn/info/1037/1146.htm
Should we remove the API?

### Error Message
(Paste the complete error message, including stack trace.)

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by leezu** [comment]
>  Should we remove the API?

The API should load the local file and provide instructions if the file is not present.
We could follow @sxjscience's proposal for GluonNLP 1.0: https://github.com/sxjscience/numpy_nlp/tree/dev/scripts/datasets

**Comment by zburning** [comment]
Actually we did not have license before, and the API fits the dataset format which was redistributed by Baidu in ERNIE repo...(not available now). https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/data/baidu_ernie_data.py#L108.
Does anyone have suggestions on how to go on?
