### ISSUE TITLE
gluonnlp.data.transforms.NLTKMosesTokenizer broken with nltk 3.3

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#115]
```
>>> import nltk
>>> print(nltk)
<module 'nltk' from '/usr/local/lib/python2.7/dist-packages/nltk/__init__.pyc'>
>>> print(nltk.__version__)
3.3
>>>
>>> import gluonnlp as nlp
>>> nlp.data.NLTKMosesTokenizer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gluonnlp/data/transforms.py", line 175, in __init__
    raise ImportError('NLTK or relevant packages are not installed. You must install NLTK '
ImportError: NLTK or relevant packages are not installed. You must install NLTK in order to use the NLTKMosesTokenizer. You can refer to the official installation guide in https://www.nltk.org/install.html .
```

If I install nltk 3.2.5, it works. Does it mean nltk is broken ...?

**Comment by szha** [comment]
http://www.nltk.org/news.html?highlight=moses#id1

**Comment by eric-haibin-lin** [comment]
Should we specify nltk version in installation page

**Comment by szha** [comment]
yes, I'm doing it now.
