### ISSUE TITLE
Dataset loader bug

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#1189]
```
[1,215]<stderr>:Exception in thread Thread-24:
[1,215]<stderr>:Traceback (most recent call last):
[1,215]<stderr>:  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[1,215]<stderr>:    self.run()
[1,215]<stderr>:  File "/usr/lib/python3.6/threading.py", line 864, in run
[1,215]<stderr>:    self._target(*self._args, **self._kwargs)
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
[1,215]<stderr>:    task = get()
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
[1,215]<stderr>:    return _ForkingPickler.loads(buf.getbuffer())
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/managers.py", line 881, in RebuildProxy
[1,215]<stderr>:    return func(token, serializer, incref=incref, **kwds)
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/managers.py", line 731, in __init__
[1,215]<stderr>:    self._incref()
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/managers.py", line 786, in _incref
[1,215]<stderr>:    dispatch(conn, None, 'incref', (self._id,))
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/managers.py", line 82, in dispatch
[1,215]<stderr>:    raise convert_to_error(kind, result)
[1,215]<stderr>:multiprocessing.managers.RemoteError:
[1,215]<stderr>:---------------------------------------------------------------------------
[1,215]<stderr>:Traceback (most recent call last):
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/managers.py", line 195, in handle_request
[1,215]<stderr>:    result = func(c, *args, **kwds)
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/managers.py", line 408, in incref
[1,215]<stderr>:    raise ke
[1,215]<stderr>:  File "/usr/lib/python3.6/multiprocessing/managers.py", line 395, in incref
[1,215]<stderr>:    self.id_to_refcount[ident] += 1
[1,215]<stderr>:KeyError: '7f87ac13a5f8'
[1,215]<stderr>:---------------------------------------------------------------------------
```

**Comment by szha** [comment]
What's the status of this issue? It's unclear what this issue affects and how to reproduce it.
