### ISSUE TITLE
NameError: name 'long_description' is not defined

### ISSUE THREAD

**Issue by ghkk** [dmlc/gluon-nlp#231]
pip install -U gluonnlp
```
Looking in indexes: http://pypi.douban.com/simple
Collecting gluonnlp
  Downloading http://pypi.doubanio.com/packages/cc/60/f2d2cbedc60f338bddf7fe820d1ee695bd8e773b9fab2537b90171d9ba18/gluonnlp-0.3.3.post0.tar.gz (146kB)
    100% |████████████████████████████████| 153kB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hceoebdx/gluonnlp/setup.py", line 47, in <module>
        long_description=long_description,
    NameError: name 'long_description' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hceoebdx/gluonnlp/
```

**Comment by szha** [comment]
@ghkk my bad. patching it now

**Comment by szha** [comment]
I've updated the pip package. Should be fixed now.
