### ISSUE TITLE
Misleading error message for loading pretrained model

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#290]
```
>>> nlp.model.get_model('standard_lstm_lm_1500', dataset_name=None, pretrained=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/gluon-nlp/gluonnlp/model/__init__.py", line 110, in get_model
    return models[name](**kwargs)
  File "/home/ubuntu/gluon-nlp/gluonnlp/model/language_model.py", line 416, in standard_lstm_lm_1500
    dataset_name, vocab, pretrained, ctx, root, **predefined_args)
  File "/home/ubuntu/gluon-nlp/gluonnlp/model/language_model.py", line 189, in _get_rnn_model
    vocab = _load_vocab(dataset_name, vocab, root)
  File "/home/ubuntu/gluon-nlp/gluonnlp/model/language_model.py", line 179, in _load_vocab
    assert vocab is not None, 'Must specify vocab if not loading from predefined datasets.'
AssertionError: Must specify vocab if not loading from predefined datasets.
```
`pretrained` is already set to True. Need to fix the msg.

**Comment by szha** [comment]
The error message does say that it's not loading from predefined datasets.
