### ISSUE TITLE
word_language_model.py is broken on StandardRNN

### ISSUE THREAD

**Issue by szha** [dmlc/gluon-nlp#298]
Using 3d9df55 with mxnet-cu92==1.3.0b20180817, I ran into the following problem.

```bash
~/gluon-nlp/scripts/language_model$ python word_language_model.py --gpus 0 --emsize 200 --nhid 200 --nlayers 2 --lr 20 --epochs 750 --batch_size 20 --bptt 35 --dropout 0.2 --dropout_h 0 --dropout_i 0 --dropout_e 0 --weight_drop 0 --tied --wd 0 --alpha 0 --beta 0 --save standard_lstm_lm_200_wikitext-2
Namespace(alpha=0.0, batch_size=20, beta=0.0, bptt=35, clip=0.25, dropout=0.2, dropout_e=0.0, dropout_h=0.0, dropout_i=0.0, emsize=200, epochs=750, eval_only=False, gpus='0', log_interval=200, lr=20.0, lr_update_factor=0.1, lr_update_interval=30, model='lstm', nhid=200, nlayers=2, optimizer='sgd', save='standard_lstm_lm_200_wikitext-2', test_mode=False, tied=True, wd=0.0, weight_dropout=0.0)
[04:52:24] src/storage/storage.cc:129: Using GPUPooledRoundedStorageManager.
Traceback (most recent call last):
  File "word_language_model.py", line 419, in <module>
    train()
  File "word_language_model.py", line 365, in train
    l = joint_loss(output, y, encoder_hs, dropped_encoder_hs)
  File "/home/ubuntu/anaconda3/envs/kdd_gluon_nlp/lib/python3.6/site-packages/mxnet/gluon/block.py", line 541, in __call__
    out = self.forward(*args)
  File "/home/ubuntu/anaconda3/envs/kdd_gluon_nlp/lib/python3.6/site-packages/mxnet/gluon/block.py", line 918, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "word_language_model.py", line 243, in hybrid_forward
    l = l + self._ar_loss(*dropped_states)
  File "/home/ubuntu/anaconda3/envs/kdd_gluon_nlp/lib/python3.6/site-packages/mxnet/gluon/block.py", line 541, in __call__
    out = self.forward(*args)
TypeError: forward() missing 1 required positional argument: 'x'
```

**Comment by szhengac** [comment]
We don't have the issue with older mxnet version?

**Comment by szha** [comment]
the error was likely introduced after the last update on the language model script which includes the combined loss. fix is here https://github.com/dmlc/gluon-nlp/pull/299/files#diff-828cd25530c96f6095fe70725dc5d62fR229

**Comment by szhengac** [comment]
We definitely need to add tests on other scripts.
