### ISSUE TITLE
FP16 Support for LSTM

### ISSUE THREAD

**Issue by whamza15** [dmlc/gluon-nlp#581]
Trying to get LSTM layer work within FP16 setup. Small code below reproduces the problem. Code works fine for fp32 but does only turn in the training loop then crashes. 
forward pass is ok. It is only when you do backward() once, it crashes in the second turn in the loop.
``` python
import mxnet as mx
import mxnet.autograd as ag
from mxnet.gluon.loss import SoftmaxCrossEntropyLoss


class Net(mx.gluon.Block):
    def __init__(self, num_tags, hidden=100, **kwargs):
        super(Net,self).__init__(**kwargs)

        self.lstm = mx.gluon.rnn.LSTM(hidden_size=hidden, bidirectional=False, layout="NTC")
        self.output_layer = mx.gluon.nn.Dense(num_tags, flatten=False)


    def forward(self, batch):
        states = self.lstm.begin_state(batch.shape[0],
                                       ctx=batch.context,
                                       dtype=batch.dtype)
        output, _ = self.lstm(batch, states)
        sequence_level = output.max(axis=1)
        logits = self.output_layer(sequence_level)
        return logits

dtype = "float16"

emb_size = 128
longest = 24
batch_size = 17
num_tags = 10
ctx = mx.gpu(0)

model = Net(num_tags)
loss = SoftmaxCrossEntropyLoss()

model.initialize(init=mx.init.Xavier(), ctx=ctx)

trainer = mx.gluon.Trainer(model.collect_params(), 'sgd', optimizer_params=dict(
    learning_rate=0.1,
    multi_precision=True
))

model.cast(dtype)


for _ in range(10):

    batch = mx.nd.random_normal(0,1, shape=(batch_size, longest, emb_size), ctx=ctx)
    gold = mx.nd.cast(mx.nd.random_uniform(0,num_tags,shape=(batch_size,), ctx=ctx), dtype="int32")
    batch = batch.astype(dtype, copy=False)

    with ag.record():
        logits = model(batch)
        l = loss(logits,gold).mean()

        l.backward()

    trainer.step(1)

    print("loss='{}'".format(l.asscalar()))
```
The error I am getting is:
```
loss='2.462890625'
Traceback (most recent call last):
  File "config/test_float16.py", line 62, in <module>
    print("loss='{}'".format(l.asscalar()))
  File ".../lib/python3.4/site-packages/mxnet/ndarray/ndarray.py", line 1990, in asscalar
    return self.asnumpy()[0]
  File ".../lib/python3.4/site-packages/mxnet/ndarray/ndarray.py", line 1972, in asnumpy
    ctypes.c_size_t(data.size)))
  File ".../lib/python3.4/site-packages/mxnet/base.py", line 251, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [00:23:12] .../src/include/mxnet/././tensor_blob.h:203: Check failed: mshadow::DataType<DType>::kFlag == type_flag_ TBlob.get_with_shape: data type do not match specified type.Expected: 0 v.s. given 2
[bt] (0) libmxnet.so(dmlc::StackTrace()+0x3d) [0x7fd19318be6d]
[bt] (1) libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x1a) [0x7fd19318c15a]
[bt] (2) libmxnet.so(mshadow::Tensor<mshadow::gpu, 3, mshadow::half::half_t> mxnet::TBlob::get<mshadow::gpu, 3, mshadow::half::half_t>(mshadow::Stream<mshadow::gpu>*) const+0x15b) [0x7fd1956dd8bb]
[bt] (3) libmxnet.so(mxnet::op::CuDNNRNNOp<mshadow::half::half_t>::Backward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x101c) [0x7fd1957ea88c]
[bt] (4) libmxnet.so(mxnet::op::OperatorState::Backward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x72d) [0x7fd19348785d]
[bt] (5) libmxnet.so(mxnet::imperative::PushOperator(mxnet::OpStatePtr const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode)::{lambda(mxnet::RunContext, mxnet::engine::CallbackOnComplete)#3}::operator()(mxnet::RunContext, mxnet::engine::CallbackOnComplete) const+0x35d) [0x7fd1932fe65d]
[bt] (6) libmxnet.so(std::_Function_handler<void (mxnet::RunContext), mxnet::imperative::PushOperator(mxnet::OpStatePtr const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode)::{lambda(mxnet::RunContext)#4}>::_M_invoke(std::_Any_data const&, mxnet::RunContext)+0x12) [0x7fd1932fe8f2]
[bt] (7) libmxnet.so(std::_Function_handler<void (mxnet::RunContext), mxnet::engine::ThreadedEngine::BulkAppend(std::function<void (mxnet::RunContext)>, mxnet::Context, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&)::{lambda(mxnet::RunContext)#1}>::_M_invoke(std::_Any_data const&, mxnet::RunContext)+0x48) [0x7fd1932794c8]
[bt] (8) libmxnet.so(std::_Function_handler<void (mxnet::RunContext), mxnet::engine::ThreadedEngine::BulkAppend(std::function<void (mxnet::RunContext)>, mxnet::Context, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&)::{lambda(mxnet::RunContext)#1}>::_M_invoke(std::_Any_data const&, mxnet::RunContext)+0x32) [0x7fd1932794b2]
[bt] (9) libmxnet.so(std::_Function_handler<void (mxnet::RunContext), mxnet::engine::ThreadedEngine::BulkAppend(std::function<void (mxnet::RunContext)>, mxnet::Context, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&)::{lambda(mxnet::RunContext)#1}>::_M_invoke(std::_Any_data const&, mxnet::RunContext)+0x32) [0x7fd1932794b2]

```

**Comment by szha** [comment]
This issue seems to have been fixed on MXNet's master branch, as I was able to run this with the code without error with the latest code there by building from source. Output:
```
loss='2.337890625'
loss='2.28125'
loss='2.447265625'
loss='2.232421875'
loss='2.349609375'
loss='2.36328125'
loss='2.26171875'
loss='2.265625'
loss='2.404296875'
loss='2.365234375'
```

I'm currently buildling 1.4.0.rc2 from source to see whether the fix will be included in the upcoming 1.4.0 release.
