### ISSUE TITLE
cannot download MRPC dataset

### ISSUE THREAD

**Issue by BerenLuthien** [dmlc/gluon-nlp#609]
Other dataset can be downloaded though.
It looks that other datasets are all downloadable, and in the download_glue_data.py only the MRPC link is different from other datasets' links.

Any help ? Thanks

https://gluon-nlp.mxnet.io/model_zoo/bert/index.html

`python3 download_glue_data.py --data_dir glue_data --tasks MRPC`
gives this error:

Processing MRPC...
Traceback (most recent call last):
  File "download_glue_data.py", line 137, in <module>
    sys.exit(main(sys.argv[1:]))
  File "download_glue_data.py", line 129, in main
    format_mrpc(args.data_dir, args.path_to_mrpc)
  File "download_glue_data.py", line 61, in format_mrpc
    urllib.request.urlretrieve(MRPC_TRAIN, mrpc_train_file)
  File "/home/ubuntu/anaconda3/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/ubuntu/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ubuntu/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/ubuntu/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/ubuntu/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/ubuntu/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by eric-haibin-lin** [comment]
Unfortunately we cannot host MRPC due to license issues. Could you shoot me an email at haibin.lin.aws@gmail.com ?

**Comment by eric-haibin-lin** [comment]
download link: https://www.microsoft.com/en-us/download/details.aspx?id=52398
