### ISSUE TITLE
race condition when horovod is used

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#726]
When launching multiple processes with horovod, downloading data may introduce race condition: 
```
  File "run_pretraining_hvd.py", line 255, in <module>
    start_step=args.start_step)
  File "/home/ec2-user/gluon-nlp/scripts/bert/pretraining_utils.py", line 44, in get_model_loss
    pretrained=pretrained, ctx=ctx)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/gluonnlp-0.6.0-py3.6.egg/gluonnlp/model/__init__.py", line 151, in get_model
  File "/home/ec2-user/.local/lib/python3.6/site-packages/gluonnlp-0.6.0-py3.6.egg/gluonnlp/model/bert.py", line 612, in bert_24_1024_16
  File "/home/ec2-user/.local/lib/python3.6/site-packages/gluonnlp-0.6.0-py3.6.egg/gluonnlp/model/bert.py", line 680, in get_bert_model
  File "/home/ec2-user/.local/lib/python3.6/site-packages/gluonnlp-0.6.0-py3.6.egg/gluonnlp/model/utils.py", line 270, in _load_vocab
  File "/home/ec2-user/.local/lib/python3.6/site-packages/gluonnlp-0.6.0-py3.6.egg/gluonnlp/data/utils.py", line 310, in _load_pretrained_vocab
  File "/usr/lib64/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/.mxnet/models/book_corpus_wiki_en_cased-2d62af22.zip'
```

**Comment by eric-haibin-lin** [comment]
```
[1,61]<stdout>:Downloading /home/ec2-user/.mxnet/models/1561012789.4379516book_corpus_wiki_en_uncased-a6607397.zip from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/g$
uon/dataset/vocab/book_corpus_wiki_en_uncased-a6607397.zip...
[1,63]<stdout>:Downloading /home/ec2-user/.mxnet/models/1561012789.4379427book_corpus_wiki_en_uncased-a6607397.zip from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/g$
uon/dataset/vocab/book_corpus_wiki_en_uncased-a6607397.zip...
[1,17]<stderr>:Traceback (most recent call last):
[1,17]<stderr>:  File "run_pretraining_hvd.py", line 270, in <module>
[1,17]<stderr>:    start_step=args.start_step)
[1,17]<stderr>:  File "/fsx/mx-0525-web-conv-4x/scripts/bert/pretraining_utils.py", line 80, in get_model_loss
[1,17]<stderr>:    pretrained=pretrained, ctx=ctx)
[1,17]<stderr>:  File "/fsx/mx-0525-web-conv-4x/src/gluonnlp/model/__init__.py", line 151, in get_model
[1,17]<stderr>:    return models[name](**kwargs)
[1,17]<stderr>:  File "/fsx/mx-0525-web-conv-4x/src/gluonnlp/model/bert.py", line 645, in bert_12_768_12
[1,17]<stderr>:    pretrained_allow_missing=pretrained_allow_missing, **kwargs)
[1,17]<stderr>:  File "/fsx/mx-0525-web-conv-4x/src/gluonnlp/model/bert.py", line 843, in get_bert_model
[1,17]<stderr>:    bert_vocab = _load_vocab(dataset_name, vocab, root, cls=BERTVocab)
[1,17]<stderr>:  File "/fsx/mx-0525-web-conv-4x/src/gluonnlp/model/utils.py", line 271, in _load_vocab
[1,17]<stderr>:    vocab = _load_pretrained_vocab(dataset_name, root, cls)
[1,17]<stderr>:  File "/fsx/mx-0525-web-conv-4x/src/gluonnlp/data/utils.py", line 341, in _load_pretrained_vocab
[1,17]<stderr>:    raise ValueError('Downloaded file has different hash. Please try again.')
[1,17]<stderr>:ValueError: Downloaded file has different hash. Please try again.
```
