### ISSUE TITLE
BERT example crashes when using MXNet naive engine

### ISSUE THREAD

**Issue by TaoLv** [dmlc/gluon-nlp#730]
It works well when `MXNET_ENGINE_TYPE` is unset.
Environment:
```shell
(gluonnlp-py3) [lvtao1@mlt-gpu207 bert]$ pip list
Package    Version        Location
---------- -------------- --------------------------------------
certifi    2019.3.9
chardet    3.0.4
gluonnlp   0.6.0          /home/lvtao1/Workspace/gluon-nlp-3/src
graphviz   0.8.4
idna       2.8
mxnet      1.5.0b20190525
numpy      1.14.6
pip        19.0.3
requests   2.21.0
setuptools 41.0.0
six        1.12.0
urllib3    1.24.2
wheel      0.33.1

```
Error log:
```shell
(gluonnlp-py3) [lvtao1@mlt-gpu207 bert]$ python finetune_classifier.py --task_name MRPC --batch_size 32 --optimizer bertadam --epochs 1 --lr 2e-5 --max_len 128 --only_inference --model_parameter ./output_dir/model_bert_MRPC_2.params --pad --dev_batch_size 1
[10:52:25] src/engine/engine.cc:55: MXNet start using engine: NaiveEngine
INFO:root:Namespace(accumulate=None, batch_size=32, bert_dataset='book_corpus_wiki_en_uncased', bert_model='bert_12_768_12', dev_batch_size=1, epochs=1, epsilon=1e-06, gpu=None, log_interval=10, lr=2e-05, max_len=128, model_parameters='./output_dir/model_bert_MRPC_2.params', only_inference=True, optimizer='bertadam', output_dir='./output_dir', pad=True, pretrained_bert_parameters=None, seed=2, task_name='MRPC', warmup_ratio=0.1)
INFO:root:loading model params from ./output_dir/model_bert_MRPC_2.params
<model architecture>
INFO:root:processing dataset...
INFO:root:Now we are doing evaluation on dev with cpu(0).
INFO:root:[Batch 10/408] loss=0.4793, metrics:f1:0.6000,accuracy:0.9000
INFO:root:[Batch 20/408] loss=0.3724, metrics:f1:0.5500,accuracy:0.8500
INFO:root:[Batch 30/408] loss=0.3786, metrics:f1:0.5667,accuracy:0.8333
INFO:root:[Batch 40/408] loss=0.5535, metrics:f1:0.5750,accuracy:0.8500
INFO:root:[Batch 50/408] loss=0.0884, metrics:f1:0.5600,accuracy:0.8600
INFO:root:[Batch 60/408] loss=0.2810, metrics:f1:0.6167,accuracy:0.8667
INFO:root:[Batch 70/408] loss=0.0490, metrics:f1:0.6286,accuracy:0.8857
INFO:root:[Batch 80/408] loss=0.3837, metrics:f1:0.6625,accuracy:0.8875
INFO:root:[Batch 90/408] loss=0.4702, metrics:f1:0.6556,accuracy:0.8778
INFO:root:[Batch 100/408] loss=0.6682, metrics:f1:0.6600,accuracy:0.8700
INFO:root:[Batch 110/408] loss=0.0228, metrics:f1:0.6636,accuracy:0.8818
INFO:root:[Batch 120/408] loss=0.4268, metrics:f1:0.6750,accuracy:0.8833
INFO:root:[Batch 130/408] loss=0.0172, metrics:f1:0.6846,accuracy:0.8923
INFO:root:[Batch 140/408] loss=0.5646, metrics:f1:0.6714,accuracy:0.8929
INFO:root:[Batch 150/408] loss=0.8041, metrics:f1:0.6600,accuracy:0.8800
INFO:root:[Batch 160/408] loss=0.3771, metrics:f1:0.6625,accuracy:0.8812
INFO:root:[Batch 170/408] loss=0.0108, metrics:f1:0.6706,accuracy:0.8882
Traceback (most recent call last):
  File "finetune_classifier.py", line 539, in <module>
    train(task.metrics)
  File "finetune_classifier.py", line 471, in train
    metric_nm, metric_val = evaluate(dev_data, metric, segment)
  File "finetune_classifier.py", line 511, in evaluate
    for batch_id, seqs in enumerate(loader_dev):
  File "/home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 450, in __next__
    batch = pickle.loads(ret.get()) if self._dataset is None else ret.get()
  File "/home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 57, in rebuild_ndarray
    fd = fd.detach()
  File "/home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata

Segmentation fault: 11

Stack trace:
  [bt] (0) /home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2b3d7b0) [0x7f2016bcf7b0]
  [bt] (1) /usr/lib64/libc.so.6(+0x35270) [0x7f2067a02270]
  [bt] (2) /home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x233ba47) [0x7f20163cda47]
  [bt] (3) /home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x233beea) [0x7f20163cdeea]
  [bt] (4) /home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x233c095) [0x7f20163ce095]
  [bt] (5) /home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x233a175) [0x7f20163cc175]
  [bt] (6) /home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x233a99b) [0x7f20163cc99b]
  [bt] (7) /home/lvtao1/miniconda3/envs/gluonnlp-py3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2b431f0) [0x7f2016bd51f0]
  [bt] (8) /home/lvtao1/miniconda3/envs/gluonnlp-py3/bin/../lib/libstdc++.so.6(+0x9b64a) [0x7f205d3ef64a]
```

**Comment by eric-haibin-lin** [comment]
@zhreshold does data loader conflict with naive engine?

**Comment by zhreshold** [comment]
I think it might indicate some potential bugs in naive engine, especially after fork.
