### ISSUE TITLE
BiLMEncoder fails to initialize if num_layers > 1

### ISSUE THREAD

**Issue by Ishitori** [dmlc/gluon-nlp#779]
## Description
`BiLMEncoder` fails during initialization if `num_layers > 1`. Works fine when num_layers = 1, but if it is at least 2, then initialization fails with a weird message. See simplest reproducible example below.

### Error Message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/block.py", line 505, in initialize
    self.collect_params().initialize(init, ctx, verbose, force_reinit)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 830, in initialize
    v.initialize(None, ctx, init, force_reinit=force_reinit)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 400, in initialize
    if not shape_is_known(self.shape):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/utils.py", line 430, in shape_is_known
    assert dim_size > unknown_dim_size, "shape dimension size cannot be less than {}, while " \
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

## To Reproduce
```python
from gluonnlp.model import BiLMEncoder
encoder = BiLMEncoder(mode='lstm', num_layers=2, input_size=200, hidden_size=100, dropout=0.1, skip_connection=False)
encoder.initialize()
```

## Environment
`pip install gluonnlp --pre`

**Comment by Ishitori** [comment]
Added PR - https://github.com/dmlc/gluon-nlp/pull/783
